### ISSUE TITLE
Question: support of polygons with holes

### ISSUE THREAD

**Issue by vvoovv** [Botffy/polyskel#12]
Does your implementation support polygons with holes?

**Comment by Botffy** [comment]
Yep! 

![image](https://user-images.githubusercontent.com/652475/75096378-4ee4cd00-559f-11ea-8dc9-1c8c82e69dd0.png)

In the skeletonize() function there's an optional parameter `holes` that should contain a list of the holes, list of vertices given in clockwise order (while the outer polygon should be given as a list of vertices in counterclockwise order)

**Comment by vvoovv** [comment]
Sorry, I should have read the description more carefully. It mention that holes can be processed.
There is also an example of a polygon with holes https://github.com/Botffy/polyskel/blob/master/examples/holey
