### ISSUE TITLE
Question: implementation Stefan Huber's algorithm

### ISSUE THREAD

**Issue by vvoovv** [Botffy/polyskel#13]
Have you thought of implementing Stefan Huber's algorithm mentioned in the README file?

**Comment by Botffy** [comment]
Well, sometimes I've entertained the thought of creating something better, yes. But it's a complicated problem, and not really my expertise. And there are alternatives available, though AFAIK not in Python.

Huber's solution STALGO is [available](https://www.cosy.sbg.ac.at/~held/projects/sk/sk.html) by contacting [Martin Held](https://www.cosy.sbg.ac.at/~held/email.html)

**Comment by vvoovv** [comment]
Thank you for the answer!

I always had that method in mind. But I only managed to create a straight skeleton for convex polygons without holes where only edge events occur.
