### ISSUE TITLE
Question: direction of Y-axis

### ISSUE THREAD

**Issue by vvoovv** [Botffy/polyskel#14]
Is my understanding correct that Y-axis points downwards?

I drew that conclusion by examining the test data set [examples/rectangle](https://github.com/Botffy/polyskel/blob/master/examples/rectangle):
40, 40
40, 310
520, 310
520, 40

**Comment by Botffy** [comment]
Yes, that's correct.

**Comment by vvoovv** [comment]
Thanks.
