### ISSUE TITLE
Incorrect result for a symmetrical polygon with a hole

### ISSUE THREAD

**Issue by vvoovv** [Botffy/polyskel#19]
I run _demo.py hole_failed.txt_
[hole_failed.txt](https://github.com/Botffy/polyskel/files/5182977/hole_failed.txt)
and got:
![image](https://user-images.githubusercontent.com/613295/92385846-4909a000-f11b-11ea-9653-5b392194a9ba.png)

**Comment by Botffy** [comment]
Oh my god, that doesn't look very nice, does it.

Sorry about that, and thanks for reporting it. There's always trouble with highly symmetrical concave polygons. I can't promise a speedy fix, but I'll try to look into it.

(PRs are always welcome)

**Comment by Botffy** [comment]
Fixed! Sorry about the delay. I explained the issue and the fix in the commit message.

(I feel like such a genius when I fix a bug caused by my earlier idiocy)
